# 1. DLT

We mark 20 points on the chessboard for which we find the 2D-3D correspondances using pixel co-ordinates and `images/Section-1/calib-object-legend.jpg`.

We estimate P using the SVD method. We decompose it to K, R and C using QR decomposition.

In [13]:
# import libraries
%matplotlib tk
import cv2
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.cm as cm
import numpy as np

imgpath = 'topdown1.png'
img = cv2.imread(imgpath)

In [11]:
# Interactive window to collect points from the image

# This cell opens a new window. 
# Clicking anywhere on the image should 
# give you the pixel location of the image. 
# Once you're done clicking, close the image window. 
image_points = []
fig = plt.figure(figsize=(80,120))

img = mpimg.imread(imgpath)

def onclick(event):
    ix, iy = event.xdata, event.ydata
    image_points.append([ix, iy])

cid = fig.canvas.mpl_connect('button_press_event', onclick)

imgplot = plt.imshow(img)
plt.show()

In [12]:
# This cell displays the points you have clicked.
N = len(image_points)
image_points = np.array(image_points)
fig = plt.figure(figsize=(10,15))

img = mpimg.imread(imgpath)
imgplot = plt.imshow(img)

colors = np.random.rand(N)
area = (30 * np.ones(N))**2 

plt.scatter(image_points[:,0], image_points[:,1], c=colors, s=area)
plt.show()

np.savetxt(f'{imgpath[:-4]}_image_points_2D.txt', image_points)





In [15]:
# World Points
# Since the image is a badmiton court, we can define the coordinates as follows
LEFT_BOUNDARY_X = 0
LEFT_SIDELINE_X = 0.46
CENTRE_LINE_X = 0.46 + 2.59
RIGHT_SIDELINE_X = 0.46 + 2.59 + 2.59
RIGHT_BOUNDARY_X = 0.46 + 2.59 + 2.59 + 0.46
BOTTOM_BOUNDARY_Y = 0
BOTTOM_LONG_SERVICE_LINE  = 0.76
BOTTOM_SHORT_SERVICE_LINE = 0.76 + 3.96
NET_Y = 0.76 + 3.96 + 1.98
NET_HEIGHT = 1.55
TOP_SHORT_SERVICE_LINE = 0.76 + 3.96 + 3.96
TOP_LONG_SERVICE_LINE = 0.76 + 3.96 + 3.96 + 3.96
TOP_BOUNDARY_Y = 0.76 + 3.96 + 3.96 + 3.96 + 0.76

# Define the coordinates of the checkerboard corners in the world coordinate frame
objp = np.zeros((1, 32, 3), np.float32)

# objp[0, 0:5, 0] = [LEFT_BOUNDARY_X,LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X]
# objp[0, 0:5, 1] = np.ones(5) * BOTTOM_BOUNDARY_Y
# objp[0, 0:5, 2] = [0, 0, 0, 0, 0]
# objp[0, 5:10, 0] = [LEFT_BOUNDARY_X,LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X]
# objp[0, 5:10, 1] = np.ones(5) * BOTTOM_LONG_SERVICE_LINE
# objp[0, 5:10, 2] = [0, 0, 0, 0, 0]
# objp[0, 10:15, 0] = [LEFT_BOUNDARY_X,LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X]
# objp[0, 10:15, 1] = np.ones(5) * BOTTOM_SHORT_SERVICE_LINE
# objp[0, 10:15, 2] = [0, 0, 0, 0, 0]
# objp[0, 15:17, 0] = [LEFT_BOUNDARY_X, RIGHT_BOUNDARY_X]
# objp[0, 15:17, 1] = np.ones(2) * NET_Y
# objp[0, 15:17, 2] = [1.55, 1.55] 
# objp[0, 17:22, 0] = [LEFT_BOUNDARY_X,LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X]
# objp[0, 17:22, 1] = np.ones(5) * TOP_SHORT_SERVICE_LINE
# objp[0, 17:22, 2] = [0, 0, 0, 0, 0]
# objp[0, 22:27, 0] = [LEFT_BOUNDARY_X,LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X]
# objp[0, 22:27, 1] = np.ones(5) * TOP_LONG_SERVICE_LINE
# objp[0, 22:27, 2] = [0, 0, 0, 0, 0]
# objp[0, 27:32, 0] = [LEFT_BOUNDARY_X,LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X]
# objp[0, 27:32, 1] = np.ones(5) * TOP_BOUNDARY_Y
# objp[0, 27:32, 2] = [0, 0, 0, 0, 0]

objp[0, 0, 0] = CENTRE_LINE_X
objp[0, 0, 1] = BOTTOM_BOUNDARY_Y
objp[0, 0, 2] = 0
objp[0, 1, 0] = CENTRE_LINE_X
objp[0, 1, 1] = BOTTOM_LONG_SERVICE_LINE
objp[0, 1, 2] = 0
objp[0, 2:7, 0] = [LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X, RIGHT_BOUNDARY_X]
objp[0, 2:7, 1] = np.ones(5) * BOTTOM_SHORT_SERVICE_LINE
objp[0, 2:7, 2] = [0, 0, 0, 0, 0]
objp[0, 7:9, 0] = [LEFT_BOUNDARY_X, RIGHT_BOUNDARY_X]
objp[0, 7:9, 1] = np.ones(2) * NET_Y
objp[0, 7:9, 2] = [0,0]
objp[0, 9:14, 0] = [LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X, RIGHT_BOUNDARY_X]
objp[0, 9:14, 1] = np.ones(5) * TOP_SHORT_SERVICE_LINE
objp[0, 9:14, 2] = [0, 0, 0, 0, 0]
objp[0, 14:19, 0] = [LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X, RIGHT_BOUNDARY_X]
objp[0, 14:19, 1] = np.ones(5) * TOP_LONG_SERVICE_LINE
objp[0, 14:19, 2] = [0, 0, 0, 0, 0]
objp[0, 19:24, 0] = [LEFT_SIDELINE_X, CENTRE_LINE_X, RIGHT_SIDELINE_X, RIGHT_BOUNDARY_X, RIGHT_BOUNDARY_X]
objp[0, 19:24, 1] = np.ones(5) * TOP_BOUNDARY_Y
objp[0, 19:24, 2] = [0, 0, 0, 0, 0]




world_points = objp[0]

image_points = np.loadtxt(f'{imgpath[:-4]}_image_points_2D.txt')
# # Converting to homogeneous coordinates
# ones = np.ones((world_points.shape[0], 1))
# world_points = np.concatenate((world_points, ones), axis = 1)
# image_points = np.concatenate((image_points, ones), axis = 1)

# ret, camera_matrix, distortion_coefficients, rotation_vectors, translation_vectors = cv2.calibrateCamera([world_points], [image_points], (img.shape[1], img.shape[0]), None, None)
# distortion_params = distortion_coefficients.ravel()


In [17]:
# DLT

def DLT(image_points, world_points):
    """
    This function takes in the image points and world points and returns the projection matrix.
    """
    n = world_points.shape[0]
    M = []    
    for i in range(n):
        x,y = image_points[i][0],image_points[i][1]
        X,Y,Z = world_points[i][0],world_points[i][1],world_points[i][2]
        M.append([X, Y, Z, 1, 0, 0, 0, 0, -x*X, -x*Y, -x*Z, -x])
        M.append([0, 0, 0, 0, X, Y, Z, 1, -y*X, -y*Y, -y*Z, -y])
    U, S, V = np.linalg.svd(np.array(M))
    P = V[-1, :]/V[-1, -1]
    P=np.reshape(P,(3,4))
    return P

import numpy as np

def DLT_with_distortion(image_points, world_points, distortion_params):
    """
    This function takes in the image points, world points, and distortion parameters and returns the projection matrix.
    """
    n = world_points.shape[0]
    M = []    
    for i in range(n):
        x, y = image_points[i][0], image_points[i][1]
        X, Y, Z = world_points[i][0], world_points[i][1], world_points[i][2]
        
        # Apply radial distortion
        r2 = x**2 + y**2
        radial_distortion = 1 + distortion_params[0] * r2 + distortion_params[1] * r2**2 + distortion_params[4] * r2**3
        x_distorted = x * radial_distortion
        y_distorted = y * radial_distortion
        
        M.append([X, Y, Z, 1, 0, 0, 0, 0, -x_distorted*X, -x_distorted*Y, -x_distorted*Z, -x_distorted])
        M.append([0, 0, 0, 0, X, Y, Z, 1, -y_distorted*X, -y_distorted*Y, -y_distorted*Z, -y_distorted])
    
    U, S, V = np.linalg.svd(np.array(M))
    P = V[-1, :] / V[-1, -1]
    P = np.reshape(P, (3, 4))
    
    return P


In [19]:
def dewarp(P, img_path, reprojected_points):
    """
    This function takes in the projection matrix and the image path and returns the dewarped image.
    """
    img = cv2.imread(img_path)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    h, w, _ = img.shape
    X_image = reprojected_points
    # Use the reprojected points to find the bounding box of the court
    min_x = np.min(X_image[:,0])
    max_x = np.max(X_image[:,0])
    min_y = np.min(X_image[:,1])
    max_y = np.max(X_image[:,1])
    # Define the destination points
    dst = np.array([[min_x, min_y], [max_x, min_y], [max_x, max_y], [min_x, max_y]])
    # Define the source points
    src = np.array([[0, 0], [w, 0], [w, h], [0, h]])
    # Find the homography matrix
    H, _ = cv2.findHomography(src, dst)
    # Warp the image
    dewarped_img = cv2.warpPerspective(img, H, (w, h))
    return dewarped_img

    
def get_reprojected_points(P, X_world):
    """
    This function takes in the projection matrix and the world points and returns the reprojected points.
    """
    X_image = P @ X_world.T
    X_image = X_image/X_image[2]
    return X_image.T

def visualise(P,X_world,img_path):
    """
    This function takes in the projection matrix, the world points and the image path and plots the reprojected points on the dewarped.
    """
    X_image = get_reprojected_points(P, X_world)
    dewarped_img = dewarp(P, img_path, X_image)
    # reprojection error
    # error = np.sum(np.sqrt(np.sum((X_image - image_points[:,:2])**2, axis=1)))
    # print("Reprojection error: ", error)
    fig = plt.figure(figsize=(10,15))
    plt.imshow(dewarped_img)
    plt.scatter(X_image[:,0], X_image[:,1], c='r', s=50)
    # # create a wireframe 
    # for i in range(0,20,5):
    #     plt.plot(X_image[i:i+5,0], X_image[i:i+5,1], c='r')
    # for i in range(5):
    #     plt.plot(X_image[i::5,0], X_image[i::5,1], c='r')
    plt.show()
    



In [20]:
# QR Decomposition

def decompose(P):
    """
    This function takes in the projection matrix and returns the K, R and t.
    """
    K, R = np.linalg.qr(P[:, 0:3])
    t = np.linalg.inv(K) @ P[:, 3]
    print(K)
    print(R)
    print(t)

In [28]:
P = DLT_with_distortion(image_points, world_points, distortion_params)
visualise(P, world_points, imgpath)
decompose(P)

NameError: name 'distortion_params' is not defined

# 2. RANSAC 

RANSAC loop 
1. Get four point correspondences (randomly) 
2. Compute H using DLT 
3. Count inliers using reprojection error
4. Keep H if largest number of inliers 
• Recompute H using all inliers


In [21]:
# function to uniformly sample 6 integers from 0 to n-1

def sample_6(n):
    """
    This function takes in the number of points and returns 6 random integers.
    """
    return np.random.choice(n, 6, replace=False)

# RANSAC

def RANSAC(image_points, world_points, n_iter=100000, threshold=0.01):
    """
    This function takes in the image points, world points, number of iterations and threshold and returns the projection matrix.
    """
    n = image_points.shape[0]
    max_inliers = 0
    for i in range(n_iter):
        idx = sample_6(n)
        P = DLT(image_points[idx], world_points[idx])
        X_image = get_reprojected_points(P, world_points)
        dist = np.linalg.norm(X_image-image_points, axis=1)
        inliers = np.sum(dist<threshold)
        if inliers>max_inliers:
            max_inliers = inliers
            P_best = P
    return P_best

P_ransac = RANSAC(image_points, world_points)
visualise(P_ransac, world_points, imgpath)
decompose(P_ransac)



/tmp/ipykernel_9628/3856481083.py:15: RuntimeWarning: divide by zero encountered in divide
  P = V[-1, :]/V[-1, -1]
/tmp/ipykernel_9628/3856481083.py:15: RuntimeWarning: invalid value encountered in divide
  P = V[-1, :]/V[-1, -1]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [ ]:
# Save the projection matrix
np.savetxt(f'{imgpath}_projection_matrix.txt', P_ransac)

# 3. Triangulation


    Linear triangulation (Hartley ch 12.2 pg 312) to find the 3D point X
    u = P1 * X and v = P2 * X. We solve AX = 0.

In [31]:
# Select points for image 1

image1_points = []
fig = plt.figure(figsize=(80,120))

img = mpimg.imread(imgpath)

def onclick(event):
    ix, iy = event.xdata, event.ydata
    image1_points.append([ix, iy])

cid = fig.canvas.mpl_connect('button_press_event', onclick)

imgplot = plt.imshow(img)
plt.show()

In [33]:
# Select points for image 2

image2_points = []
fig = plt.figure(figsize=(80,120))

imgpath2 = 'fronton.png'
img = mpimg.imread(imgpath2)

def onclick(event):
    ix, iy = event.xdata, event.ydata
    image2_points.append([ix, iy])

cid = fig.canvas.mpl_connect('button_press_event', onclick)

imgplot = plt.imshow(img)
plt.show()

In [32]:
# This cell displays the points you have clicked.
N = len(image1_points)
image_points = np.array(image1_points)
fig = plt.figure(figsize=(10,15))

img = mpimg.imread(imgpath)
imgplot = plt.imshow(img)

colors = np.random.rand(N)
area = (15 * np.ones(N))**2 

plt.scatter(image_points[:,0], image_points[:,1], c=colors, s=area)
plt.show()

In [27]:
# This cell displays the points you have clicked.
N = len(image2_points)
image_points = np.array(image2_points)
fig = plt.figure(figsize=(10,15))

img = mpimg.imread(imgpath2)
imgplot = plt.imshow(img)

colors = np.random.rand(N)
area = (15 * np.ones(N))**2 

plt.scatter(image_points[:,0], image_points[:,1], c=colors, s=area)
plt.show()

In [34]:
# DLT

world_points = np.array([
    [0,0,0], [1,0,0], [2,0,0], [3,0,0], [3,0,1], [3,0,2], [3,0,3],
    [0,1,0], [1,1,0], [2,1,0], [3,1,0], [3,1,1], [3,1,2], [3,1,3],
    [0,2,0], [1,2,0], [2,2,0], [3,2,0], [3,2,1], [3,2,2], [3,2,3],
    [0,3,0], [1,3,0], [2,3,0], [3,3,0], [3,3,1], [3,3,2], [3,3,3]])

def visualise(P,X_world,img_path):
    """
    This function takes in the projection matrix, the world points and the image path and plots the reprojected points on the image.
    """
    X_image = get_reprojected_points(P, X_world)
    # reprojection error
    # error = np.sum(np.sqrt(np.sum((X_image - image_points[:,:2])**2, axis=1)))
    # print("Reprojection error: ", error)
    fig = plt.figure(figsize=(10,15))
    img=mpimg.imread(img_path)
    imgplot = plt.imshow(img)
    plt.scatter(X_image[:,0], X_image[:,1], c='r', s=50)
    plt.show()

# Converting to homogeneous coordinates
ones = np.ones((world_points.shape[0], 1))
world_points = np.concatenate((world_points, ones), axis = 1)
image1_points = np.concatenate((image1_points, ones), axis = 1)
image2_points = np.concatenate((image2_points, ones), axis = 1)

P1 = DLT(image1_points, world_points)
visualise(P1, world_points, imgpath)
decompose(P1)

P2 = DLT(image2_points, world_points)
visualise(P2, world_points, imgpath2)
decompose(P2)


[[-9.99999941e-01 -5.01512430e-05  3.41194921e-04]
 [ 5.00746878e-05 -9.99999974e-01 -2.24378664e-04]
 [ 3.41206164e-04 -2.24361565e-04  9.99999917e-01]]
[[-1.54099342e+02  9.33668628e+01 -3.56610284e+02]
 [ 0.00000000e+00  3.45507196e+02 -6.60779250e+00]
 [ 0.00000000e+00  0.00000000e+00  2.02053346e-01]]
[-1.46306452e+03 -2.11572306e+03  1.02451978e+00]
[[-9.73412951e-01 -2.29050701e-01  1.73281362e-03]
 [ 2.29050096e-01 -9.73414485e-01 -5.42402744e-04]
 [ 1.81098361e-03 -1.31080730e-04  9.99998352e-01]]
[[ -37.77077946    3.6296836  -333.99235955]
 [   0.          323.84904824  -80.83477086]
 [   0.            0.            0.64561706]]
[-8.0218842e+02 -2.2187818e+03  2.1619141e+00]


In [36]:
def linear_triangulation(u, v, P1, P2):
    """
    :param u, v: 2D points in homo. or catesian coordinates. Shape (3 x n)
    :param P1, P2: Camera matrices associated with u and v. Shape (3 x 4)
    :param centre2: Camera centres associated with v. Shape (3 x 1)
    :returns: 4 x n homogenous 3d triangulated points
    """

    num_points = u.shape[1] 
    res = np.ones((4, num_points))
    t = -P2[:,3].T @ P2[:,0:3]
    for i in range(num_points):
        A = np.asarray([
            ((u[0, i]) * P1[2, :] - P1[0, :]),
            ((u[1, i]) * P1[2, :] - P1[1, :]),
            ((v[0, i]) * P2[2, :] - P2[0, :]),
            ((v[1, i]) * P2[2, :] - P2[1, :])
        ])

        _, _, V = np.linalg.svd(A)
        X = V[-1, :4]
        res[:, i] = X / X[3]
        
    
    return res

# Triangulation
X = linear_triangulation(image1_points.T, image2_points.T, P1, P2)
print(X)

# Visualise the 3D points
fig = plt.figure(figsize=(10,10))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(X[0,:], X[1,:], X[2,:], c='r', s=50)
plt.show()

# Save the 3D points as an image to ../results/Section-3/3D_points.png
fig.savefig('../results/Section-3/3D_points.png')

# Calculate the error between the predicted world coordinate and the original world coordinate
world_points = world_points[:,:3]
error = np.linalg.norm(X[:3,:].T - world_points, axis=1).mean()
print("Error: ", error)


[[ 0.02303745  0.95188561  2.01579724  2.98614262  3.03353413  3.00146078
   2.96385593  0.0163133   0.91738909  2.09037507  2.96113854  3.08204516
   3.00938694  2.95573087 -0.0262498   0.93382591  2.01497218  2.94821227
   3.02430298  3.10875459  2.99164103  0.0180184   1.03676839  2.05808946
   2.93018791  2.97566511  3.01021258  2.96385461]
 [ 0.01617498  0.05932359  0.0285451  -0.03664925  0.03136595  0.01171407
   0.00700464  0.96793146  0.8462075   0.98542962  1.0002695   1.07766693
   0.91958799  0.86471017  2.03369722  2.01094063  2.02430266  2.01356406
   2.08006472  2.1500542   2.034112    3.02151123  3.01587133  2.99082753
   2.90346854  2.97060377  3.00145576  2.97987068]
 [-0.03743874 -0.03597129 -0.02884661  0.05677262  1.00307246  2.07109328
   2.98065505  0.00717025  0.04556323 -0.03737099  0.01961065  0.90615314
   2.0408488   3.00658629  0.04860409  0.04888389 -0.01212465  0.01798875
   0.96843464  1.8954495   3.02737614  0.02493989 -0.0532781  -0.06057443
   0.03948